"""add_full_text_index_for_product

Revision ID: 7a6887a80cf5
Revises: 798b3012175f
Create Date: 2026-04-29 19:12:34.023708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a6887a80cf5'
down_revision: Union[str, Sequence[str], None] = '798b3012175f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('index_products_title_fulltext', 'products', ['title'], unique=False, mysql_prefix='FULLTEXT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_products_title_fulltext', table_name='products', mysql_prefix='FULLTEXT')
    # ### end Alembic commands ###
